name: google-bard
version: '1.0.0'
summary: Google Bard Desktop
description: |
  An unofficial desktop app for Google Bard.
  
  This is a desktop app for Google Bard https://bard.google.com/, a chatbot that uses Generative AI to have conversations with you.
  
  Build based on https://github.com/mantreshkhurana/Google-Bard-electron repository.
base: core22
build-snaps:
  - gnome-42-2204/latest/candidate
confinement: strict
grade: stable
architectures:
  - amd64

apps:
  google-bard:
    command: "google-bard --no-sandbox"
    extensions: [gnome]
    # desktop: meta/ui/google-bard.desktop
    plugs:
    - browser-support
    - network
    - network-bind
    - desktop
    - desktop-legacy
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  google-bard:
    plugin: nil
    source: https://github.com/mantreshkhurana/Google-Bard-electron.git
    source-tag: 1.0.0
    override-build: |
        # workaround for build.snapcraft.io builds
        # https://bugs.launchpad.net/bugs/1886861
        if [ -n "$http_proxy" ]; then
          export ELECTRON_GET_USE_PROXY=1
          export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
          export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
        fi
        mkdir -p snap/gui
        echo -e "[Desktop Entry]\nName=Google Bard\nX-GNOME-FullName=Google Bard\nComment=Google Bard Desktop\nCategories=GNOME;Utility;\nExec=google-bard\nIcon=\${SNAP}/meta/gui/google-bard.png\nTerminal=false\nType=Application\nVersion=1.0.0" > snap/gui/google-bard.desktop
        cp assets/icons/png/favicon.png snap/gui/google-bard.png
        npm install electron electron-packager
        npm run package-linux
        cp -rv ./release-builds/Google\ Bard-linux-x64/* $CRAFT_PRIME 
        mv $CRAFT_PRIME/Google\ Bard $CRAFT_PRIME/google-bard
    build-snaps:
    - node/20/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
    - libc6
